using NUnit.Framework;
using ConsoleApp.TestPrograms;

namespace ConsoleApp.TestProgramsTest
{
    [TestFixture]
    public class Test1Test
    {
        [Test]
        void CharCountTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}